Initial upload
husarion/rosbot-xl-snap pull request #1
Opened 2023-09-19 08:23 UTC by artivis

Initial upload of the `rosbot-xl` snap.

2023-09-28 13:44 UTC, Kotochleb requested changes
Works fine on hardware. The only problems were with setting parameters and BLAS. Suggestions are pending. Also I suggested small change in the reamde.

2023-09-28 13:44 UTC, Kotochleb commented on snap/hooks/configure
> +  esac
```suggestion
  case "${MECANUM}" in
    "true")
      snapctl set mecanum=True
      ;;
    "1")
      snapctl set mecanum=True
      ;;
    "false")
      snapctl set mecanum=False
      ;;
    "0")
      snapctl set mecanum=False
      ;;
    "True") ;;
    "False") ;;
    *)
    	>&2 echo "'${MECANUM}' is not a supported value for 'mecanum'." \
        "Possible values are True, False, true, false, 1, 0"
    	return 1
    	;;
  esac
```

2023-09-28 13:44 UTC, Kotochleb commented on snap/hooks/configure
> +  esac
```suggestion
  case "${CAMERA_MOUNT}" in
    "true")
      snapctl set include-camera-mount=True
      ;;
    "1")
      snapctl set include-camera-mount=True
      ;;
    "false")
      snapctl set include-camera-mount=False
      ;;
    "0")
      snapctl set include-camera-mount=False
      ;;
    "True") ;;
    "False") ;;
    *)
    	>&2 echo "'${CAMERA_MOUNT}' is not a supported value for 'include-camera-mount'." \
        "Possible values are True, False, true, false, 1, 0"
    	return 1
    	;;
  esac
```

2023-09-28 13:44 UTC, Kotochleb commented on README.md
> +- [rosbot-xl-nav](https://snapcraft.io/rosbot-xl-nav)
```suggestion
> **Note**
> This snap is part of an integrated snaps deployment.
> 
> Other recommended snaps to be installed are,
> 
> - [micro-xrce-dds-agent](LINK)
> - [sllidar-ros2](https://snapcraft.io/sllidar-ros2)
> - [rosbot-xl-teleop](https://snapcraft.io/rosbot-xl-teleop)
> - [rosbot-xl-nav](https://snapcraft.io/rosbot-xl-nav)
```

2023-09-28 13:44 UTC, Kotochleb commented on snap/snapcraft.yaml
> +    plugs: [network, network-bind]
```suggestion
    plugs: [network, network-bind]
    environment:
      LD_LIBRARY_PATH:  "$LD_LIBRARY_PATH:$SNAP/opt/ros/underlay_ws/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/opt/ros/underlay_ws/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
```

2023-10-04 14:43 UTC, Kotochleb commented on snap/snapcraft.yaml
> +    plugs: [network, network-bind]
Since this problem was resolved on the snap level itself it now works fine and this change is not needed

2023-10-06 15:12 UTC, Kotochleb approved these changes
After all of the discussions, it looks and works good. I am closing this PR

2023-10-06 15:12 UTC, merged

2023-10-06 15:13 UTC, Guillaumebeuzeboc commented on README.md
> +snap install rosbot-xl
CI is pushing on candidate and edge, and the uploaded snap is only available on `beta` should the channel be specified?

2023-10-06 15:13 UTC, Guillaumebeuzeboc commented on README.md
> +snap install rosbot-xl
Also sudo is required.

2023-10-06 15:13 UTC, Guillaumebeuzeboc commented on README.md
> +snap set rosbot-xl mecanum=True
sudo is required here too.